### ISSUE TITLE
LICENSE file missing

### ISSUE THREAD

**Issue by sebastianschauenburg** [sigio/ansible-openprovider-zone#1]
I'm looking for the LICENSE file. The README states that this code is BSD licensed, but which BSD license exactly?
Personally I like the GPL(v3 currently) and want to make some contributions or fork, hence my questions ;-)

**Comment by sigio** [comment]
Any OpenSource license is fine with me.... it's not that revollutionary..... on an ansible repo I created today I picked MIT, which is also fine with me :)

**Comment by sigio** [comment]
Added license.txt and updated to MIT
